import "./components/header";
import "./components/aos";
import "./components/modal";
import "./components/scrollToTop";
import "./components/burger";
import "./components/dynamic_adapt";
import "./components/swiper";
import "./components/accordion";
import "./components/validate-forms";
